stages:
  - build
    #  - test
    #  - deploy

variables:
  VERSION: "1.0.0"
  IMAGE_TAG: "$CI_REGISTRY/$CI_PROJECT_PATH/$APP_NAME:$CI_COMMIT_SHORT_SHA"

default:
  image: gitlab:8050/arvan/runner-images:dind
  tags: [stage]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  after_script:
    - docker rmi "$IMAGE_TAG" || true

build-image:
  stage: build
  variables:
    APP_NAME: "app"
  script:
    - docker build -t "$IMAGE_TAG" "$APP_NAME"
    - docker push "$IMAGE_TAG"
  tags: [stage]
  except:
    - schedules
  retry: 2

    #test-app:
    #  stage: test
    #
    #deploy-app:
    #  stage: deploy


