stages:
  - build
  - test
  - deploy

variables:
  VERSION: "1.0.0"
  IMAGE_TAG: "$CI_REGISTRY/$CI_PROJECT_PATH/$APP_NAME:$CI_COMMIT_SHORT_SHA"
  APP_NAME: "app"

default:
  image: gitlab:8050/arvan/runner-images:dind
  tags: [stage]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  after_script:
    - docker rmi "$IMAGE_TAG" || true

build-image:
  stage: build
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
  except:
    - schedules
  retry: 2

deploy-app:
  stage: deploy
  script:
    - docker compose down app || true
    - docker images | grep "$DOCKER_REGISTRY/$CI_PROJECT_PATH" | awk '{print $3}' | xargs docker rmi -f || true
    - docker compose up -d 
  after_script: []

test-app:
  stage: test
  image: docker.arvancloud.ir/python:3.13
  before_script: []
  script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - pytest tests/
  after_script: []


