---
services:
  app:
    image: ${IMAGE_TAG}
    container_name: app
    hostname: app
    restart: always
      ## git ignore
    environment:
      APP_TITLE: ${APP_TITLE}
      APP_DESCRIPTION: ${APP_DESCRIPTION}
      APP_VERSION: ${APP_VERSION}
      APP_DEBUG: ${APP_DEBUG}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: docker.arvancloud.ir/postgres:15-alpine
    container_name: db
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
        #### port mismatch??????
    expose:
      - "${DB_PORT}"
    networks:
      - app_net


networks:
  app_net:
    name: app_net

volumes:
  db_data:
    name: db_data
